version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install -g aws-cli
      - npm install -g @aws-amplify/cli
  
  pre_build:
    commands:
      - echo "Pre-build phase"
      - sed -i.bak "s/{applicationId}/$APPLICATION_ID/g" template.json
      - aws cloudformation deploy --template-file template.json --stack-name disability-rights-texas-stack --parameter-overrides ApplicationId=$APPLICATION_ID --capabilities CAPABILITY_IAM
      - echo "Extracting CloudFormation outputs"
      - cd frontend
      - echo "Creating .env file"
      - npm install
  
  build:
    commands:
      - echo "Building React application"
      - npm run build
      - amplify init -y
      - echo "Deploying to Amplify"
      - echo "Creating zip file"
      - zip -r ../build.zip build/
      - echo "Uploading to S3"
      - aws s3 cp ../build.zip s3://$ARTIFACT_BUCKET/build.zip
      - echo "Getting presigned URL"
      - echo "Starting Amplify job"
  
  post_build:
    commands:
      - echo "Deployment completed"

artifacts:
  base-directory: frontend/build
  files:
    - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"