version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo "Installing dependencies"
      - npm install -g aws-cli
  
  pre_build:
    commands:
      - echo "Pre-build phase"
      - cd frontend
      - echo "# API Configuration" > .env
      - echo "REACT_APP_BASE_API_ENDPOINT=https://example.com/api" >> .env
      - echo "REACT_APP_DEFAULT_LANGUAGE=EN" >> .env
      - npm install
  
  build:
    commands:
      - echo "Building React application"
      - npm run build
      - echo "Skipping Amplify initialization due to credential issues"
  
  post_build:
    commands:
      - echo "Build completed successfully"
      - echo "Artifacts will be available in the build directory"

artifacts:
  base-directory: frontend/build
  files:
    - "**/*"

cache:
  paths:
    - "frontend/node_modules/**/*"