version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_API_ENDPOINT=${REACT_APP_BASE_API_ENDPOINT}
      - REACT_APP_API_ENDPOINT=${REACT_APP_API_ENDPOINT}
      - REACT_APP_FEEDBACK_ENDPOINT=${REACT_APP_FEEDBACK_ENDPOINT}
      - REACT_APP_AWS_REGION=${REACT_APP_AWS_REGION}
      - REACT_APP_LAMBDA_FUNCTION=${REACT_APP_LAMBDA_FUNCTION}
      - REACT_APP_APPLICATION_ID=${REACT_APP_APPLICATION_ID}
      - REACT_APP_DEFAULT_LANGUAGE=${REACT_APP_DEFAULT_LANGUAGE}
    volumes:
      - ./:/app
      - /app/node_modules